:toc: true
:author: Gerd Aschemann
:email: gerd@aschemann.net

= Ich Denk An Dich

====
.TL;DR
A _birthday_ present for my beloved wife Katrin Rabow <3

_Ich Denk An Dich_ is German meaning _I am thinking of you_.

She always wanted to get a short notice every day that I was remembering her and thinking of her.
Unfortunately I am a so called Nerd.
Sometimes (at least for some hours a day) I dive into a tunnel and will not even recognize a fire alarm in the same building.

But then - she is a great woman - she came up with a very practical solution: Why not write a mobile app to remind me every now and then to send her a message.
I think it is not a replacement for a trigger in my brain to remember my family in the real world but probably a good work around.

So I took some time to learn how to write a mobile app with the great <<sec:flutter,Flutter>> framework.
Hope to get it ready by 2020-06-30!

By {author} (mailto:{email}[{email}])
====

== Features

=== Usage Features

* [x] Run on Android and iOS (for the latter only tested on emulator so far, cf. <<sec:problems:ios>>)
* [x] Enable to launch external applications to send the message
* [x] Add target person's name (TextField)
* [x] Select Date/Time for OneTime Reminder
* [x] Show scheduled time + cancel button
* [x] Show _repeat after 24h_ check box (and repeat notification after 24h, of course)
* [x] Edit greeting message and copy to clipboard to paste

=== Developer Features

* [x] Use nice logger
* [x] Initial documentation

== TODOs

=== Features

==== Usage Features

* [ ] Select Date/Time range for random/frequent Reminders
* [ ] Select Days-of-Week choice for Frequent Reminders
* [ ] List of Applications as Pre-Selection
* [ ] Forward Text / TargetPerson to Application
* [ ] Add snooze button to Popup
* [ ] Show warning when selected time is in past

==== Developer Features

* [ ] Modularize code (split up to several files at least)
* [ ] Add automated tests (should do that with each new feature, of course)

=== Marketing

* [ ] Prepare product description for Android Playstore
* [ ] Prepare introduction Tweet series

=== Build / Deployment

* [ ] Deploy to Android Store
** Get Application Id: https://developer.android.com/studio/build/application-id.html

=== Problems

[[sec:problems:ios]]
==== iOS

* [ ] Extend iOS version: works in general but cannot generate notifications on emulator
* [ ] Deliver to real (testing) device

[[sec:flutter]]
== Flutter

This project was originally generated by Flutter itself.
All subsequent changes are my fault!

A few resources to get you started if this is your first Flutter project:

* https://flutter.dev/docs/get-started/codelab[Lab: Write your first Flutter app]
* https://flutter.dev/docs/cookbook[Cookbook: Useful Flutter samples]

For help getting started with Flutter, view our
https://flutter.dev/docs[online documentation], which offers tutorials,
samples, guidance on mobile development, and a full API reference.

=== Dependencies

[source,yaml]
----
include::pubspec.yaml[tag=dependencies]
----